name: Packer Build

on:
    push:
        branches:
        - main  # Change this to your main branch name
    pull_request:
        branches:
            - main  # Change this to your main branch name

jobs:
    build:
        runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
        uses: actions/checkout@v2

        - name: Set up Packer
        uses: hashicorp/setup-packer@v1.11.1
        with:
            version: 1.11.1  # Adjust the Packer version as needed

        - name: Build Ubuntu Server Image
        run: |
            packer build -var 'vm_name=ubuntu18-network' ubuntu.pkr.hcl  # Adjust your Packer build command here

        - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
            name: ubuntu-server-ova
            path: output3/*.ova  # Adjust the path to match your Packer output

